config/routes.rb
Rails.application.routes.draw do
  root "doctors#index"

  resources :doctors do
    resources :patients, only: [:index, :new,:create]
  end

  resources :patients
  resources :appointments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord 
  belongs_to :doctor 
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord 
  has_many :appointments
  has_many :patients , through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord 
  has_many :appointments 
  has_many :doctors , through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController 
  before_action :set_appointment, only: [:edit, :update, :destroy]
  def index
    @appointments = Appointment.all
  end
  def show 
    @appointment = Appointment.find(params[:id])
  end
  def new 
    @appointment = Appointment.new
  end
  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save 
      redirect_to @appointment
    else 
      render :new ,status: :unprocessable_entity
    end
  end 
  def edit 
    
  end 
  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment, notice: 'Appointment was successfully updated.'
    else
      render :edit
    end
  end 
  def destroy
    @appointment.destroy
    redirect_to appointments_path, notice: 'Appointment was successfully destroyed.'
  end 

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end


  def appointment_params
    params.require(:appointment).permit(:name, :phone_number,:time, :doctor_id, :patient_id)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show 
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor, notice: 'Doctor was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor, notice: 'Doctor was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path, status: :see_other, notice: 'Doctor was successfully destroyed.'
  end

  private

  def set_doctor 
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all
  end

  def show 
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to @patient, notice: 'Patient was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: 'Patient was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path, status: :see_other, notice: 'Patient was successfully destroyed.'
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: @appointment, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name%>
  </div>

  <div>
    <%= form.label :phone_number%>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :time %>
    <%= form.datetime_select :time %>
  </div>
<div class="field">
  <%= form.label :patient_id, "Patient" %>
  <%= form.collection_select :patient_id, Patient.all, :id, :name, { prompt: 'Select a Patient' } %>
</div>

<div class="field">
  <%= form.label :doctor_id, "Doctor" %>
  <%= form.collection_select :doctor_id, Doctor.all, :id, :name, { prompt: 'Select a Doctor' } %>
</div>

   
  <div>
    <%= form.submit "Create Appointment" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1> Edit Appointment</h1>

<%= render "form", appointment: @appointment %> 

app/views/appointments/index.html.erb
<h1>Appointments</h1>

<ul>
  <% @appointments.each do |appointment| %>
    <li>
    <%=appointment.name%>
    </li>
    <li>
    <%=appointment.phone_number%>
    </li>
    <li>
    <%=appointment.time%>
    </li>
    <li>
    <%=appointment.doctor_id%>
    </li>
    <li>
    <%=appointment.patient_id%>
    </li>
  <% end %>
</ul>

app/views/appointments/new.html.erb
<h1>Appointments</h1>

<%= render "form", appointment: @appointment %>

app/views/appointments/show.html.erb
<h1><%=@appointment.name%></h1> 
<h1><%=@appointment.phone_number%></h1> 
<h1><%=@appointment.time%></h1>
<h1><%=@appointment.doctor_id%></h1>
<h1><%=@appointment.patient_id%></h1>

  <ul>
    <li><%= link_to "Edit", edit_appointment_path(@appointment) %></li>
    <li><%= link_to "Destroy", appointment_path(@appointment), data:{ turbo_method: :delete, turbo_confirm: :"Are you sure"}%></li>
  </ul> 

app/views/doctors/_form.html.erb
<%= form_with(model: @doctor, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.submit "Save Doctor" %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1> Edit Doctor</h1>

<%= render "form", doctor: @doctor %> 

app/views/doctors/index.html.erb
<h1>Doctors</h1>

<ul>
  <% @doctors.each do |doctor| %>
    <li> 
    <%= link_to doctor.name, doctor_path(doctor) %>
     <li><%= link_to "Edit", edit_doctor_path(doctor) %></li>
    </li>
   
  <% end %>
</ul> 

app/views/doctors/new.html.erb
<h1>Doctor</h1>

<%= render "form", doctor: @doctor %>

app/views/doctors/show.html.erb
  <h1><%=@doctor.name%></h1> 
  <ul>
    <li><%= link_to "Destroy", doctor_path(@doctor), data:{ turbo_method: :delete, turbo_confirm: :"Are you sure"}%></li>
  </ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hospital" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "New Doctor", new_doctor_path %>
    <%= link_to "New Patient", new_patient_path %>
    <%= link_to "New Appointment", new_appointment_path%>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: @patient, local:true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age, required: true %>
  </div>

  <div>
    <%= form.submit "Add Patient" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1> Edit Patients</h1>

<%= render "form", patient: @patient %> 

app/views/patients/index.html.erb
<h1>Patients</h1>

<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= link_to "#{patient.name} (#{patient.age})", patient_path(patient) %>
    </li>
  <% end %>
</ul>

app/views/patients/new.html.erb
<h1>Patient</h1>
<%=render "form", patient: @patient %>

app/views/patients/show.html.erb
<h1><%= @patient.name %></h1> 
<h2>Age: <%= @patient.age %></h2>

<ul>
  <li><%= link_to "Edit Patient", edit_patient_path(@patient) %></li>
   <li><%= link_to "Destroy", patient_path(@patient), data:{ turbo_method: :delete, turbo_confirm: :"Are you sure"}%></li>
</ul>